app/views/user.py
"""
Views:
    - `sign_up (/signup)`: Register a new user in the system
    - `login (/login)`: Sign in to an existing account
    - `logout (/logout)`: Sing out from current account
    - `profile (/profile)`: User profile with functions:
        - Shows user vacancies
        - Create a new vacancy
"""
# pylint: disable=ungrouped-imports
# pylint: disable=logging-fstring-interpolation

import json
import logging
from flask import Blueprint, request, redirect, url_for, render_template, flash
from flask_login import login_user, logout_user, login_required, current_user
from flask_admin.contrib.sqla import ModelView
from app.service.auth_service import util_signup, util_login
from app.service.vacancy_service import VacancyService
from app.service.user_service import UserService
from app.configs.config import TestBaseConfig


auth_view = Blueprint("auth", __name__)


@auth_view.route("/signup", methods=["GET", "POST"])
def sign_up():
    """
    Registration account
    :return: rendered template
    """
    if request.method == "POST":
        logging.info("User POST data through registration form")
        email = request.form.get("emailAddress")
        password_1 = request.form.get("password1")
        password_2 = request.form.get("password2")
        user = util_signup(email, password_1, password_2)
        if user:
            login_user(user)

            return redirect(url_for("base.home"))
        flash("Problem with registration", category='error')

    return render_template("user/registration.html")


@auth_view.route("/login", methods=["GET", "POST"])
def login():
    """
    Log in account
    :return: rendered template
    """
    if request.method == "POST":
        logging.info("User POST data through login form")
        email = request.form.get("emailAddress")
        password = request.form.get("password")

        user_status, user_error_msg, user = util_login(email, password)

        if user_status:
            logging.info("Login user")
            login_user(user, remember=True)
            return redirect(url_for("auth.profile"))

        flash(f"Problem - {user_error_msg}", category='error')

    return render_template("user/login.html")


@auth_view.route("/logout", methods=["GET"])
@login_required
def logout():
    """
    Sing out
    :return: rendered template
    """
    logging.info("Logout user")
    logout_user()
    return redirect(url_for("base.home"))


@auth_view.route("/profile", methods=["GET", "DELETE"])
@login_required
def profile():
    """
    Profile of the user with his vacancies and the ability to create new ones
    Can delete own vacancies
    :return: rendered template
    """
    if request.method == "DELETE":
        data = json.loads(request.data)
        logging.info(f"Deleted data - {data['name']}")
        if data["name"]:
            VacancyService.delete_vacancy_by_name_user(data["name"], current_user.id)
        return "Deleted"

    logging.info("User open profile")
    user = UserService.find_user_by_email(current_user.email)
    content = {"user": current_user, "exists_vacancies": user.vacancies}
    return render_template("user/profile.html", **content)


class JobAdminModelView(ModelView):
    """
    User admin check
    """
    def is_accessible(self):
        """
        Check whether the user is registered and logged in as an administrator
        """
        if not current_user.is_authenticated or current_user.email != TestBaseConfig.ADMIN_MAIL:
            return False
        return True

    def inaccessible_callback(self, name, **kwargs):
        """
        Redirects to the registration page
        """
        return redirect(url_for('auth.login'))

app/views/vacancies.py
"""
Views:
    - `categories_show (/categories)`: Show all jobs categories
    - `vacancies_show (/<category_slug>)`: Show all vacancies for specific category
    - `vacancy_create (/vacancy_create)`: Show vacancy create form
    - `vacancy_detail (/vacancy/<vacancy_slug>)`: Show detail about vacancy
"""
# pylint: disable=logging-fstring-interpolation
# pylint: disable=wrong-import-order
# pylint: disable=ungrouped-imports
# pylint: disable=simplifiable-if-statement

import logging
import json
from flask import Blueprint, render_template, request, redirect, url_for
from flask_mail import Message
from flask_login import current_user, login_required
from app.configs.config import TestBaseConfig
from app.service.validartors import VacancyFormValidator
from app.service.category_service import CategoryService
from app.service.vacancy_service import VacancyService
from app.service.user_service import UserService
from app import mail


vacancies_view = Blueprint('vacancies', __name__)


@vacancies_view.route("/categories", methods=["GET"])
def categories_show():
    """
    Show categories
    :return: rendered template
    """
    logging.info("Show all categories")
    categories = CategoryService.get_all_categories()
    average_salary = {}
    all_count_vacancies = 0
    for category in categories:
        average = 0
        for vacancy in category.vacancies:
            average += vacancy.salary
        if average > 0:
            average_salary[category.name] = int(average / len(category.vacancies))
        else:
            average_salary[category.name] = 0
        all_count_vacancies += len(category.vacancies)
    content = {"categories": categories, "count_vacancies": all_count_vacancies,
               "average_salary": average_salary, "user": current_user}
    logging.info(f"All categories - {categories}")
    return render_template("categories.html", **content)


@vacancies_view.route("/vacancy_create", methods=["GET", "POST"])
@login_required
def vacancy_create():
    """
    Vacancy information form (Name, salary, about, notification, contacts).
    Then the vacancy appears in the list
    :return: rendered template
    """
    if request.method == "POST":
        logging.info("User POST vacancy_create")
        vacancy_name = request.form.get("name")
        vacancy_salary = request.form.get("salary")
        vacancy_about = request.form.get("about")
        vacancy_contacts = request.form.get("contacts")
        vacancy_category = request.form.get("category")
        if request.form.get("notify"):
            vacancy_notification = True
        else:
            vacancy_notification = False
        logging.info("Get vacancy data from vacancy creating form")
        validator = VacancyFormValidator(vacancy_name, vacancy_salary,
                                         vacancy_about, vacancy_contacts)
        vacancy_name = validator.check_name()
        vacancy_salary = validator.check_salary()
        logging.info("Validation is DONE")

        category = CategoryService.find_category_by_name(vacancy_category)
        VacancyService.create_new_vacancy(vacancy_name, vacancy_salary,
                                          vacancy_about, vacancy_contacts,
                                          vacancy_notification, current_user.id, category.id)
        logging.info("New vacancy created")

        return redirect(url_for("auth.profile"))

    categories = CategoryService.get_all_categories()
    content = {"categories": categories, "user": current_user}
    return render_template("vacancy_create.html", **content)


@vacancies_view.route("/<category_slug>/vacancies", methods=["GET", "POST"])
def vacancies_show(category_slug):
    """
    Show vacancies specific category
    Filters salary vacancies
    :param category_slug: used for url
    :return: rendered template
    """
    page_count = request.args.get("page", 1, type=int)
    if request.method == "POST":
        salary_average = request.form.get("salary-avg")
        if salary_average:
            logging.info(f"Salary filter get - {salary_average}")
            salary_average = float(salary_average)
            category = CategoryService.find_category_by_slug(category_slug)
            vacancies = VacancyService.find_vacancies_by_filter(
                                          category.id, salary_average,
                                          (page_count, TestBaseConfig.PAGINATION_PAGE))
            logging.info(f"Current category - {category.name}")
            logging.info(f"All filtered vacancies - {vacancies}")
            content = {"category_vacancies": vacancies, "category_slug": category_slug,
                       "user": current_user, "filter_flag": True}
            return render_template("vacancies.html", **content)

    category = CategoryService.find_category_by_slug(category_slug)
    if category:
        vacancies = VacancyService.find_vacancies_by_category(category.id,
                                                              (page_count,
                                                               TestBaseConfig.PAGINATION_PAGE))
        content = {"category_vacancies": vacancies, "category_slug": category_slug,
                   "user": current_user, "filter_flag": False}
        return render_template("vacancies.html", **content)
    return redirect(url_for("base.home"))


@vacancies_view.route("/vacancy/<vacancy_slug>", methods=["GET", "POST"])
@login_required
def vacancy_detail(vacancy_slug):
    """
    Show detail about specific vacancy (title, salary, information about vacancy, contacts)
    :param vacancy_slug:
    :return: rendered template
    """
    if request.method == "POST":
        data = json.loads(request.data)
        if data["notification"]:
            current_vacancy = VacancyService.find_vacancy_by_slug(vacancy_slug)
            owner = UserService.find_user_by_id(current_vacancy.user)
            if current_user.id != owner.id:
                msg = Message("Someone watch your contacts", sender=TestBaseConfig.MAIL_USERNAME,
                              recipients=[owner.email])
                msg.body = f"Someone found out about your job " \
                           f"in this vacancy - {current_vacancy.name}"
                mail.send(msg)
                return "Message sent"
            return "Message don't send"

    current_vacancy = VacancyService.find_vacancy_by_slug(vacancy_slug)
    logging.info(f"Show vacancy detail - {current_vacancy.name}")
    content = {"vacancy": current_vacancy, "user": current_user}
    return render_template("vacancy.html", **content)

app/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Module area title -->
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Module area css -->
    {% block css %}
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
</head>
<body class="background-style">
    <!-- Module area content -->
    {% block content %}
    {% endblock %}

    <!-- Module area js -->
    {% block js %}
    {% endblock %}

    <!-- Module area flash -->

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
</body>
</html>

app/templates/user/login.html
{% extends 'user/base.html' %}
{% block title %}Registration{% endblock %}
{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Логін</h3>
            <form method="post">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label" for="emailAddress">Емейл:</label>
                    <input type="email" id="emailAddress" name="emailAddress" class="form-control form-control-lg" />
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label" for="password">Пароль:</label>
                    <input type="password" id="password" name="password" class="form-control form-control-lg" />
                  </div>
                </div>
              </div>
                
              <div class="mt-4 pt-2">
                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
              </div>
                
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

app/templates/user/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock %}
{% block content %}
    <div class="p-5 text-center">
        <div class="mask" style="background-color: #f8f9fa;">
          <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white">
                <h1 class="mb-3" style="color: grey; font-size: 65px;">Профіль</h1>
                <h1 class="mb-3" style="color: grey; font-size: 35px;">{{ user.email }}</h1>
                <button style="font-weight: 700;
                      color: white;
                      text-decoration: none;
                      padding: .8em 1em calc(.8em + 3px);
                      border-radius: 3px;
                      background: rgb(64,199,129);
                      box-shadow: 0 -3px rgb(53,167,110) inset;
                      transition: 0.2s;;">
                    <a style="text-decoration: none;" href="{{ url_for('vacancies.vacancy_create') }}">Створити</a></button>
                {% for vac in exists_vacancies|reverse %}
                    <div class="card" style="margin-top: 15px">
                        <div class="card-body">
                            <div class="card-body" style="margin: 20px">
                                <a class="vac-title" style="text-decoration: none; font-size: 20px;"
                                   href="{{ url_for('vacancies.vacancy_detail', vacancy_slug=vac.slug) }}">{{ vac.name }}</a>
                                <button class="deleteMe" style="background: red; margin-left: 30px;
                                color: #fff; border-radius: 3px;
                                font-size: 18px; line-height: 1;">Видалити</button>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
          </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{{ url_for('static', filename='js/profile.js') }}"></script>
{% endblock %}

app/templates/user/registration.html
{% extends 'user/base.html' %}
{% block title %}Registration{% endblock %}
{% block content %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Реєстрація</h3>
            <form method="post">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label" for="emailAddress">Емейл:</label>
                    <input type="email" id="emailAddress" name="emailAddress" class="form-control form-control-lg" />
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label" for="password1">Пароль:</label>
                    <input type="password" id="password1" name="password1" class="form-control form-control-lg" />
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <label class="form-label" for="password2">Підтвердити пароль:</label>
                    <input type="password" id="password2" name="password2" class="form-control form-control-lg" />
                  </div>
                </div>
              </div>

              <div class="mt-4 pt-2">
                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}