app/views/about.py
"""
Views:
    - `about (/about)`: Show page with author information
"""
# pylint: disable=logging-fstring-interpolation

import logging
from flask import Blueprint, render_template
from flask_login import current_user


about_view = Blueprint('author', __name__)


@about_view.route("/about", methods=["GET"])
def about():
    """
    Show about page
    :return: rendered template
    """
    logging.info(f"Enter to about page - {current_user}")
    return render_template("about.html", user=current_user)

app/views/error.py
"""
Views:
    - `page_not_found (404)`: Show page with 404 error
    - `page_timeout (408)`: Show page with 408 error
"""

from flask import render_template, make_response, Blueprint

error_view = Blueprint("errors", __name__)


@error_view.app_errorhandler(404)
def page_not_found(error):
    """
    Create page with info about 404 error
    :param error: Instance error with information about problem
    :return: response with html template and status
    """
    return make_response(render_template("errors.html", status=error), 404)


@error_view.app_errorhandler(408)
def page_timeout(error):
    """
    Create page with info about 408 error
    :param error: Instance error with information about problem
    :return: response with html template and status
    """
    return make_response(render_template("errors.html", status=error), 408)

app/views/vacancies.py
"""
Views:
    - `categories_show (/categories)`: Show all jobs categories
    - `vacancies_show (/<category_slug>)`: Show all vacancies for specific category
    - `vacancy_create (/vacancy_create)`: Show vacancy create form
    - `vacancy_detail (/vacancy/<vacancy_slug>)`: Show detail about vacancy
"""
# pylint: disable=logging-fstring-interpolation
# pylint: disable=wrong-import-order
# pylint: disable=ungrouped-imports
# pylint: disable=simplifiable-if-statement

import logging
import json
from flask import Blueprint, render_template, request, redirect, url_for
from flask_mail import Message
from flask_login import current_user, login_required
from app.configs.config import TestBaseConfig
from app.service.validartors import VacancyFormValidator
from app.service.category_service import CategoryService
from app.service.vacancy_service import VacancyService
from app.service.user_service import UserService
from app import mail


vacancies_view = Blueprint('vacancies', __name__)


@vacancies_view.route("/categories", methods=["GET"])
def categories_show():
    """
    Show categories
    :return: rendered template
    """
    logging.info("Show all categories")
    categories = CategoryService.get_all_categories()
    average_salary = {}
    all_count_vacancies = 0
    for category in categories:
        average = 0
        for vacancy in category.vacancies:
            average += vacancy.salary
        if average > 0:
            average_salary[category.name] = int(average / len(category.vacancies))
        else:
            average_salary[category.name] = 0
        all_count_vacancies += len(category.vacancies)
    content = {"categories": categories, "count_vacancies": all_count_vacancies,
               "average_salary": average_salary, "user": current_user}
    logging.info(f"All categories - {categories}")
    return render_template("categories.html", **content)


@vacancies_view.route("/vacancy_create", methods=["GET", "POST"])
@login_required
def vacancy_create():
    """
    Vacancy information form (Name, salary, about, notification, contacts).
    Then the vacancy appears in the list
    :return: rendered template
    """
    if request.method == "POST":
        logging.info("User POST vacancy_create")
        vacancy_name = request.form.get("name")
        vacancy_salary = request.form.get("salary")
        vacancy_about = request.form.get("about")
        vacancy_contacts = request.form.get("contacts")
        vacancy_category = request.form.get("category")
        if request.form.get("notify"):
            vacancy_notification = True
        else:
            vacancy_notification = False
        logging.info("Get vacancy data from vacancy creating form")
        validator = VacancyFormValidator(vacancy_name, vacancy_salary,
                                         vacancy_about, vacancy_contacts)
        vacancy_name = validator.check_name()
        vacancy_salary = validator.check_salary()
        logging.info("Validation is DONE")

        category = CategoryService.find_category_by_name(vacancy_category)
        VacancyService.create_new_vacancy(vacancy_name, vacancy_salary,
                                          vacancy_about, vacancy_contacts,
                                          vacancy_notification, current_user.id, category.id)
        logging.info("New vacancy created")

        return redirect(url_for("auth.profile"))

    categories = CategoryService.get_all_categories()
    content = {"categories": categories, "user": current_user}
    return render_template("vacancy_create.html", **content)


@vacancies_view.route("/<category_slug>/vacancies", methods=["GET", "POST"])
def vacancies_show(category_slug):
    """
    Show vacancies specific category
    Filters salary vacancies
    :param category_slug: used for url
    :return: rendered template
    """
    page_count = request.args.get("page", 1, type=int)
    if request.method == "POST":
        salary_average = request.form.get("salary-avg")
        if salary_average:
            logging.info(f"Salary filter get - {salary_average}")
            salary_average = float(salary_average)
            category = CategoryService.find_category_by_slug(category_slug)
            vacancies = VacancyService.find_vacancies_by_filter(
                                          category.id, salary_average,
                                          (page_count, TestBaseConfig.PAGINATION_PAGE))
            logging.info(f"Current category - {category.name}")
            logging.info(f"All filtered vacancies - {vacancies}")
            content = {"category_vacancies": vacancies, "category_slug": category_slug,
                       "user": current_user, "filter_flag": True}
            return render_template("vacancies.html", **content)

    category = CategoryService.find_category_by_slug(category_slug)
    if category:
        vacancies = VacancyService.find_vacancies_by_category(category.id,
                                                              (page_count,
                                                               TestBaseConfig.PAGINATION_PAGE))
        content = {"category_vacancies": vacancies, "category_slug": category_slug,
                   "user": current_user, "filter_flag": False}
        return render_template("vacancies.html", **content)
    return redirect(url_for("base.home"))


@vacancies_view.route("/vacancy/<vacancy_slug>", methods=["GET", "POST"])
@login_required
def vacancy_detail(vacancy_slug):
    """
    Show detail about specific vacancy (title, salary, information about vacancy, contacts)
    :param vacancy_slug:
    :return: rendered template
    """
    if request.method == "POST":
        data = json.loads(request.data)
        if data["notification"]:
            current_vacancy = VacancyService.find_vacancy_by_slug(vacancy_slug)
            owner = UserService.find_user_by_id(current_vacancy.user)
            if current_user.id != owner.id:
                msg = Message("Someone watch your contacts", sender=TestBaseConfig.MAIL_USERNAME,
                              recipients=[owner.email])
                msg.body = f"Someone found out about your job " \
                           f"in this vacancy - {current_vacancy.name}"
                mail.send(msg)
                return "Message sent"
            return "Message don't send"

    current_vacancy = VacancyService.find_vacancy_by_slug(vacancy_slug)
    logging.info(f"Show vacancy detail - {current_vacancy.name}")
    content = {"vacancy": current_vacancy, "user": current_user}
    return render_template("vacancy.html", **content)

app/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <div class="p-5 text-center bg-image"
    style="
          background-image: url('https://mdbootstrap.com/img/new/slides/041.jpg');
          height: 570px;
          margin-top: 70px;
        ">
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
          <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white">
              <h1 class="mb-3">Автор сайту:</h1>
              <h4 class="mb-3">Максим Войціцький КН-208</h4>
            </div>
          </div>
        </div>
    <img style="height: 400px; width: 300px;"
                 src="{{ url_for('static', filename='img/author.jpg') }}" alt="Author"></a>
  </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Module area title -->
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Module area css -->
    {% block css %}
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
</head>
<body>
    {% include "common/header.html" %}
    <div class="container">
        <div class="row row-offcanvas row-offcanvas-right">
             <!-- Module area content -->
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <!-- Module area js -->
    {% block js %}
    {% endblock %}
</body>
</html>

app/templates/categories.html
{% extends 'base.html' %}
{% block title %}Categories{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}
{% block content %}
    <h1 class="categories-title">Категорії. Кількість вакансій - {{ count_vacancies }}</h1>
    <div class="row row-cols-1 row-cols-md-4 g-4">
      {% for category in categories %}
        <div class="col">
          <div class="card">
            <div class="card-body">
                <a style="text-decoration: none;" href="{{ url_for('vacancies.vacancies_show', category_slug=category.slug) }}">
                    <h4 class="card-title">{{ category.name }}</h4></a>
                <p>Number: {{ category.vacancies|length }}</p>
                <p>Average salary: {{ average_salary[category.name] }}$</p>
                {% set img_name = "img/" + category.name + ".png" %}
                <img src="{{ url_for('static', filename=img_name) }}" height="95" width="95">
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
{% endblock %}

app/templates/errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/main_page.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div
          class="p-5 text-center bg-image"
          style="
          background-image: url('https://mdbootstrap.com/img/new/slides/041.jpg');
          height: 500px;
          margin-top: 70px;
        ">
        <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
          <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white">
              <h1 class="mb-3">About project</h1>
              <h4 class="mb-3">This is web application which help people find job</h4>
            </div>
          </div>
        </div>
  </div>
{% endblock %}

app/templates/vacancies.html
{% extends 'base.html' %}
{% block title %}Vacancies{% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
{% endblock %}
{% block content %}
    <h1 class="categories-title">Вакансії</h1>
    {% if filter_flag %}
        {% for vac in category_vacancies.items|reverse %}
            <div class="card" style="width: 800px;">
              <h5 class="card-header">{{ vac.name }}</h5>
              <div class="card-body">
                <h5 class="card-title">Зарплата: {{ vac.salary }}$</h5>
                <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ vac.info }}</p>
                <a href="{{ url_for('vacancies.vacancy_detail', vacancy_slug=vac.slug) }}" class="btn btn-primary">Go</a>
              </div>
            </div>
        {% endfor %}
    {% else %}
        {% for vac in category_vacancies.items|reverse %}
            <div class="card" style="width: 800px;">
              <h5 class="card-header">{{ vac.name }}</h5>
              <div class="card-body">
                <h5 class="card-title">Зарплата: {{ vac.salary }}$</h5>
                <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ vac.info }}</p>
                <a href="{{ url_for('vacancies.vacancy_detail', vacancy_slug=vac.slug) }}" class="btn btn-primary">Go</a>
              </div>
            </div>
        {% endfor %}
    {% endif %}
    <div>
        <article class="card-group-item" style="position: absolute; left: 1200px; bottom: 650px;">
            <header class="card-header"><h6 class="title">Середня зарплата</h6></header>
            <div class="filter-content">
                <div class="card-body">
                    <form method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

                        <label class="btn">
                          <input type="checkbox" name="salary-avg" value="100" onclick="onlyOne(this)">
                          <span class="form-check-label">100$</span>
                        </label>
                        <label class="btn">
                          <input type="checkbox" name="salary-avg" value="500" onclick="onlyOne(this)">
                          <span class="form-check-label">500$</span>
                        </label>
                        <label class="btn">
                          <input type="checkbox" name="salary-avg" value="1000" onclick="onlyOne(this)">
                          <span class="form-check-label">1000$</span>
                        </label>
                        <label class="btn">
                          <input type="checkbox" name="salary-avg" value="2000" onclick="onlyOne(this)">
                          <span class="form-check-label">2000$</span>
                        </label>
                        <label class="btn">
                          <input type="checkbox" name="salary-avg" value="5000" onclick="onlyOne(this)">
                          <span class="form-check-label">5000$</span>
                        </label>
                        <label class="btn">
                          <input type="checkbox" name="salary-avg" value="6500" onclick="onlyOne(this)">
                          <span class="form-check-label">6500$</span>
                        </label>

                        <button style="position: absolute; right: 480px; top: 120px;" type="submit" class="btn btn-primary">Фільтер</button>
                    </form>
                </div>
            </div>
        </article>
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% for page_num in category_vacancies.iter_pages(left_edge=1, right_edge=1,
          left_current=1, right_current=1) %}
            {% if page_num %}
                <li class="page-item">
                    <a class="page-link"
                       href="{{ url_for('vacancies.vacancies_show', category_slug=category_slug, page=page_num) }}">
                    {{ page_num }}</a></li>
            {% else %}
                ...
            {% endif %}
        {% endfor %}
      </ul>
    </nav>

{% endblock %}
{% block js %}
    <script src="{{ url_for('static', filename='js/checkbox-limit.js') }}"></script>
{% endblock %}

app/templates/vacancy.html
{% extends 'base.html' %}
{% block title %}Vacancy {% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock %}
{% block content %}
    <main role="main" class="container">
        <p class="slug-vacancy" style="display: none;">{{ vacancy.slug }}</p>
        <h1 class="mt-5">{{ vacancy.name }}</h1>
        <p style="color: #0b5ed7" class="lead">Зарплата: {{ vacancy.salary }}</p>
        <p style="margin-top: 25px;">Головна інформація:</p>
        <p>{{ vacancy.info }}</p>
        <p style="margin-top: 55px;">Контакти:</p>
        <p class="content_toggle">Показати контакти</p>
        <p class="content_block" style="display: none;">{{ vacancy.contacts }}</p>
    </main>
{% endblock %}
{% block js %}
    <script src="{{ url_for('static', filename='js/notification.js') }}"></script>
{% endblock %}

app/templates/vacancy_create.html
{% extends 'base.html' %}
{% block title %}Vacancy Form{% endblock %}
{% block content %}
    <form method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

        <div class="mb-3">
            <label for="titleFormControlInput" class="form-label">Назва вакансії</label>
            <input type="text" name="name" class="form-control" id="titleFormControlInput">
        </div>

        <div class="mb-3">
            <label for="salaryFormControlTextarea" class="form-label">Зарплата $</label>
            <input type="number" name="salary" class="form-control" id="salaryFormControlTextarea">
        </div>

        <div class="mb-3">
            <label for="aboutFormControlTextarea" class="form-label">Про вакансію</label>
            <textarea class="form-control" name="about" id="aboutFormControlTextarea" rows="4"></textarea>
        </div>

        <div class="mb-3">
            <label for="contactFormControlTextarea" class="form-label">Контактна інформація</label>
            <textarea class="form-control" name="contacts" id="contactFormControlTextarea" rows="4"></textarea>
        </div>

        <div class="form-check">
          <label class="form-check-label" for="flexCheckDefault">Нотифікація</label>
          <input class="form-check-input" name="notify" type="checkbox" id="flexCheckDefault">
        </div>

        <select name="category" class="form-select" aria-label="Default select example">
            {% for category in categories %}
                <option value="{{ category.name }}">{{ category.name }}</option>
            {% endfor %}
        </select>

        <button style="margin-top: 30px;" type="submit" class="btn btn-primary">Створити</button>
    </form>
{% endblock %}